local M = {}

local function set_highlight_groups()
	vim.api.nvim_set_hl(0, 'ColorColumn', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Conceal', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Cursor', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'CursorColumn', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'CursorLine', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'CursorLineNr', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'DiffAdd', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'DiffChange', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'DiffDelete', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'DiffText', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Directory', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'EndOfBuffer', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'ErrorMsg', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'FoldColumn', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Folded', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'IncSearch', {fg = '#e4e4ef', bg = '#404040', bold = false})
	vim.api.nvim_set_hl(0, 'MatchParen', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'ModeMsg', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'MoreMsg', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'NonText', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Pmenu', {fg = '#e4e4ef', bg = '#404040', bold = false})
	vim.api.nvim_set_hl(0, 'PmenuSbar', {fg = '#e4e4ef', bg = '#404040', bold = false})
	vim.api.nvim_set_hl(0, 'PmenuSel', {fg = '#e4e4ef', bg = '#606060', bold = false})
	vim.api.nvim_set_hl(0, 'PmenuThumb', {fg = '#e4e4ef', bg = '#606060', bold = false})
	vim.api.nvim_set_hl(0, 'Question', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'QuickFixLine', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Search', {fg = '#e4e4ef', bg = '#404040', bold = false})
	vim.api.nvim_set_hl(0, 'SignColumn', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'SpecialKey', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'SpellBad', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'SpellCap', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'SpellLocal', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'SpellRare', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'StatusLineNC', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'TabLine', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'TabLineFill', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'TabLineSel', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'VertSplit', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Visual', {bg = '#404040', bold = false})
	vim.api.nvim_set_hl(0, 'VisualNOS', {bg = '#404040', bold = false})
	vim.api.nvim_set_hl(0, 'WarningMsg', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'WildMenu', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Constant', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Error', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Identifier', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Ignore', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'PreProc', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Special', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Statement', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Todo', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Type', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Underlined', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'CursorIM', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'ToolbarLine', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'ToolbarButton', {fg = '#e4e4ef', bg = nil, bold = false})

	vim.api.nvim_set_hl(0, 'Terminal', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Normal', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'StatusLineTerm', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'StatusLine', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'StatusLineTermNC', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'StatusLineNC', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'MessageWindow', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'PopupNotification', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Todo', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Boolean', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Constant', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Character', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Constant', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Conditional', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Statement', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Define', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'PreProc', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Debug', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Special', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Delimiter', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Special', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Exception', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Statement', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Float', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Constant', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Function', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Identifier', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Include', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'PreProc', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Keyword', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Statement', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Label', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Statement', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Macro', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'PreProc', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Number', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Constant', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Operator', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Statement', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'PreCondit', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'PreProc', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Repeat', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Statement', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'SpecialChar', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Special', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'SpecialComment', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Special', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'StorageClass', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Type', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'String', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Constant', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Structure', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Type', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Tag', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Special', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Typedef', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Type', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'lCursor', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Cursor', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'debugBreakpoint', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'ModeMsg', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'debugPC', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'SignColumn', {bg = '#121212', bold = false})
	vim.api.nvim_set_hl(0, 'LineNr', {fg = '#9b9b9b', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Title', {fg = '#e4e4ef', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'Comment', {fg = '#cecece', bg = nil, bold = false})
	vim.api.nvim_set_hl(0, 'StatusLineNC', {fg = nil, bg = nil, bold = false})
end

function M.setup()
  vim.cmd('highlight clear')
  vim.cmd('syntax reset')

  vim.opt.termguicolors = true
  vim.o.background = 'dark'

  vim.g.colors_name = 'dull'
  set_highlight_groups()
end

return M
